pub mod color;
pub mod completion_handler;
pub mod download_handler;
mod github_release;
pub mod install_app_handler;
pub mod list_handler;
mod progress_bar;
pub mod remove_handler;
pub mod result;
pub mod root_command;
mod select_assets;
mod spinner;
pub mod untag_handler;
pub mod update_handler;
